### PR TITLE
Require a POST to show password

### PR DESCRIPTION
**Pull request by kaj**
Just adding a query-string to a GET url to get the password might be insecure (hostile javascript could use a users credentials).  Requiering a POST, which requires a CSRF  value, should be safer.

### CODE REVIEW

**Comment by kaj** [comment]
This works, but the fact that it renders output (rather than redirecting) on `post` requests have the downside that reloading the page after generating a password will generate a new password.

Ideal behavior would be that a reload is allways a `get` (so the password is hidden on reload).  But I don't know if that can be done.

Of course, one way it so allways `get` the page, but let javascript do a non-page `post` to get the password and injekt it into the dom tree.  But I think I'd like to avoid that if possible.

**Comment by nsg** [comment]
So, if you generates a new password, press reload and click thought the warning that you will resend the post data, you will get another password... I think that's fine :)

But you are correct, if this could be solved nicer would be a nice touch but I think, merge this and we can import it later.

:+1:

**Comment by kaj** [comment]
I think it can be fixed by pushing a location with the location api (as done in single page apps that are not completley broken).  But yes, that can be added later.

**Comment by kaj** [comment]
I think https://caniuse.com/#feat=history says the javascript should work in all relevant browsers.

**Pull request merged**
